version: '3'

services:
  app:
    container_name: ether_client
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ".:/usr/src/app"
