name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./codetobank/. --file ./codetobank/Dockerfile.dev --tag seyio/etherbank-frontend
