name: Argo CI Pipeline

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SHA8: ${GITHUB_SHA::8}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./codetobank/. --file ./codetobank/Dockerfile --tag seyio/etherbank-frontend
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: seyio/etherbank-frontend
        path: codetobank
        dockerfile: codetobank/Dockerfile
        tags: latest, ${{ steps.slug.outputs.sha8 }}
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.1.0"
    - name: Run Kustomization and Push
      run : |
        git clone https://.:${{ secrets.GIT_TOKEN }}@github.com/codetobank/etherbank-infra
        cd etherbank-infra/stage
        git config user.email "ci@ci.com"
        git config user.name "CI Tool"
        kustomize edit set image seyio/etherbank-frontend:${{ steps.slug.outputs.sha8 }}
        git commit -am '${{ steps.slug.outputs.sha8 }}' && git push || echo 'no changes'